reviews:
  profile: assertive
  poem: false
  auto_review:
    enabled: true
    base_branches:
      - "^(?!main$).*$"

knowledge_base:
  learnings:
    scope: global
  pull_requests:
    scope: auto
